### ISSUE TITLE
installation issue with cmake

### ISSUE THREAD

**Issue by Maggie490** [vice87/gam-ngs#11]
Hi, 

I have the following prerequisites installed on Linux Red Hat 6.5: 
GCC 4.4.7
boost 1.55.0
cmake 2.8.12
sparsehash 2.0.2
zlib 1.2.3

Boost, cmake, sparsehash and gam-ngs are installed locally on my user account. When cmake can't seem to find certain boost libraries (see below). The specific libraries that seem to be missing (graph, program_options, system and filesystem) are in the boost directory. I have tried it using the boost path in my .bashrc file and following the "Custom Sparsehash/Boost libraries" in the gam-ngs readme file. 

I'm fairly new to bioinformatics and linux, so I don't know what I am missing.

Thank you,
Maggie

An example cmake run:
ddashevs@Mason: ~/local/src/gam-ngs-master/build> cmake ..
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at /N/u/ddashevs/Mason/local/cmake/2.8.12.2/share/cmake-2.8/Modules/FindBoost.cmake:1111 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.55.0

  Boost include path: /N/u/ddashevs/Mason/local/src/boost_1_55_0

  Could not find the following Boost libraries:

```
      boost_graph
      boost_program_options
      boost_system
      boost_filesystem
```

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:39 (find_package)

-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.3") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Sparsehash: /N/u/ddashevs/Mason/local/sparsehash/2.0.2/include  
-- Configuring incomplete, errors occurred!

**Comment by StijnT** [comment]
I am having the same issue. Does anyone know what the problem might be?

**Comment by vice87** [comment]
I think Maggie490 problem was due to an incorrect installation/building of boost libraries.

In particular the content of the BOOST_ROOT path (provided to cmake) did not contain the "include" and "lib", suggesting that the library had compiled in a different path or had not been compiled at all.

i) in first case (i.e., the library has been correctly installed in another path): you should provide that one as -DBOOST_ROOT argument to cmake.

ii) in the second case (the library still needs to be installed/compiled): you can follow the documentation in boost website. In a nutshell, the following commands should suffice (assuming you want to build it in the same folder of the source files).

```
 $ cd /path/to/boost_x_xx_x/
 $ ./bootstrap.sh --prefix=/path/to/boost_x_xx_x --with-libraries=graph,program_options,system,filesystem
 $ ./b2 install
```

Now you can move to GAM-NGS's folder and compile the sources, as explained in the README file:

```
 $ cmake -DBOOST_ROOT=/path/to/boost_x_xx_x -DBoost_NO_BOOST_CMAKE=TRUE ..
 $ make
```

Best,
Riccardo

**Comment by StijnT** [comment]
Thank you very much for your answer. I'm fairly new to linux so it is much appreciated.

Kind regards,
Stijn Trappeniers
